/* Drop Sequence */

BEGIN 
  EXECUTE IMMEDIATE 'DROP SEQUENCE personaID_SEQ';
EXCEPTION 
  WHEN OTHERS THEN NULL;
END;
/

/* Create Sequence */

CREATE SEQUENCE personaID_SEQ
INCREMENT BY 1 
START WITH 1
;

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   CLIENTE CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   CUENTA  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/
/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   MOVIMIENTO  CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/


/* Create Tables */

CREATE TABLE CLIENTE (
    Cliente_ID       NUMBER GENERATED ALWAYS AS IDENTITY,
    Persona_ID       NUMBER NOT NULL,
    Nombre           VARCHAR2(100) NOT NULL,
    Genero           VARCHAR2(10),
    Edad             NUMBER,
    Identificacion   VARCHAR2(20) NOT NULL,
    Direccion        VARCHAR2(200),
    Telefono         VARCHAR2(20),
    Contrasena       VARCHAR2(100) NOT NULL,
    Estado           VARCHAR2(20) NOT NULL
);

CREATE TABLE CUENTA (
    Numero_Cuenta    NUMBER GENERATED ALWAYS AS IDENTITY,
    Cliente_ID       NUMBER NOT NULL,
    Tipo_Cuenta      VARCHAR2(30) NOT NULL,
    Saldo_Inicial    NUMBER(15, 2) NOT NULL,
    Estado           VARCHAR2(20) NOT NULL
);

CREATE TABLE MOVIMIENTO (
    Movimiento_Id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    Numero_Cuenta    NUMBER NOT NULL,
    Fecha            DATE NOT NULL,
    Tipo_Movimiento  VARCHAR2(30) NOT NULL,
    Valor            NUMBER(15, 2) NOT NULL,
    Saldo            NUMBER(15, 2) NOT NULL
);


/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  CLIENTE IS 'Informacion Clientes';

COMMENT ON COLUMN CLIENTE.Cliente_ID     IS 'Identificador unico del registro de la tabla corresponde a la llave primaria';
COMMENT ON COLUMN CLIENTE.Persona_ID     IS 'Identificador unico de la persona';
COMMENT ON COLUMN CLIENTE.Nombre         IS 'Nombre de la persona';
COMMENT ON COLUMN CLIENTE.Genero         IS 'Genero de la persona';
COMMENT ON COLUMN CLIENTE.Edad           IS 'Edad de la persona';
COMMENT ON COLUMN CLIENTE.Identificacion IS 'Identificacion de la persona';
COMMENT ON COLUMN CLIENTE.Direccion      IS 'Direccion de la persona';
COMMENT ON COLUMN CLIENTE.Telefono       IS 'telefono de  la persona';   
COMMENT ON COLUMN CLIENTE.Contrasena     IS 'Constraseña del cliente';
COMMENT ON COLUMN CLIENTE.Estado         IS 'Estado del cliente';

COMMENT ON TABLE  CUENTA IS 'Cuentas asociada a un cliente';

COMMENT ON COLUMN CUENTA.Numero_Cuenta  IS 'Identificador unico del registro de la tabla corresponde a la llave primaria';
COMMENT ON COLUMN CUENTA.cliente_ID     IS 'para referenciar el cliente dueno de la cuenta';
COMMENT ON COLUMN CUENTA.Tipo_Cuenta    IS 'Tipo de cuenta ';
COMMENT ON COLUMN CUENTA.Saldo_Inicial  IS 'Saldo Inicia de la cuenta';
COMMENT ON COLUMN CUENTA.estado         IS 'Estado del cliente';

COMMENT ON TABLE  MOVIMIENTO IS 'Movimientos asociados a una cuenta';

COMMENT ON COLUMN MOVIMIENTO.Movimiento_Id   IS 'Identificador unico del registro de la tabla corresponde a la llave primaria';
COMMENT ON COLUMN MOVIMIENTO.Numero_Cuenta   IS 'para refrencias la cuenta sobre las que realizan los movimientos';
COMMENT ON COLUMN MOVIMIENTO.Fecha           IS 'Fecha en la que se realiza el movimiento';
COMMENT ON COLUMN MOVIMIENTO.Tipo_Movimiento IS 'Tipo de movimiento que se realizo';
COMMENT ON COLUMN MOVIMIENTO.Valor           IS 'valor del movimiento';
COMMENT ON COLUMN MOVIMIENTO.Saldo           IS 'Saldo después del movimiento';

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  CLIENTE 
 ADD CONSTRAINT CLIENTE_PK
	PRIMARY KEY (Cliente_ID)
;

CREATE UNIQUE INDEX CLIENTE_UK1
 ON  CLIENTE (Persona_ID) 
;

ALTER TABLE  CUENTA 
 ADD CONSTRAINT CUENTA_PK
	PRIMARY KEY (Numero_Cuenta)
;
ALTER TABLE  MOVIMIENTO 
 ADD CONSTRAINT MOVIMIENTO_PK
	PRIMARY KEY (Movimiento_Id)
;

CREATE INDEX CUENTA_IX1   
 ON  CUENTA (Cliente_ID) 
;

CREATE INDEX MOVIMIENTO_IX1   
 ON  MOVIMIENTO (Numero_Cuenta) 
;

ALTER TABLE  CUENTA 
 ADD CONSTRAINT CUENTA_FK1
	FOREIGN KEY (Cliente_ID) REFERENCES  CLIENTE (Cliente_ID)
;

ALTER TABLE  MOVIMIENTO 
 ADD CONSTRAINT MOVIMIENTO_FK1
	FOREIGN KEY (Numero_Cuenta) REFERENCES  CUENTA (Numero_Cuenta)
;
